/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as ReactqueryImport } from './routes/react_query'
import { Route as CounterImport } from './routes/counter'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ReactqueryRoute = ReactqueryImport.update({
  path: '/react_query',
  getParentRoute: () => rootRoute,
} as any)

const CounterRoute = CounterImport.update({
  path: '/counter',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/counter': {
      preLoaderRoute: typeof CounterImport
      parentRoute: typeof rootRoute
    }
    '/react_query': {
      preLoaderRoute: typeof ReactqueryImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  CounterRoute,
  ReactqueryRoute,
])

/* prettier-ignore-end */
